### ISSUE TITLE
Crashes on servers

### ISSUE THREAD

**Issue by sscards55** [Immersive-Geology-Team/Immersive-Energy#1]
[latest.log](https://github.com/Immersive-Geology-Team/Immersive-Energy/files/6796558/latest.log)

**Comment by NightmareTwilight** [comment]
This is a Advanced Rocketry Crash. Please bring it to them instead.

**Comment by NightmareTwilight** [comment]
Ah, noticed the issue from IEn. Though, this should have been fixed in newer versions, too.
